sudo: false

language: go

go:
  - "1.8"
  - "1.9"
  - "1.10"

install:
  - "go version"
  - "go env"
  - "mkdir -p $GOPATH/bin"

script:
  - "make test vet"

after_success:
  - "bash <(curl -s https://codecov.io/bash)"
